//! Cluster-only validation evidence cache (RFC 015).
//!
//! The cache stores model-owned validation evidence keyed by a Loeres-generated
//! model identity and mutation epoch. It is intentionally host-side and `std`;
//! no edge crate depends on this module.

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};

use loeres::validation::ValidationScope;
use loeres::{FiniteScalar, MetricScalar, SolverError};
use loeres_backend_std::DenseVector;

use crate::model::{ClusterProjectedFirstOrderProblem, ProjectedFirstOrderFiniteEvidence};

static NEXT_MODEL_ID: AtomicU64 = AtomicU64::new(1);

/// Process-local model identity for validation-cache keys.
///
/// `0` is reserved for sentinel/non-cacheable use. Values are generated by
/// Loeres-owned carriers, not by caller-provided strings or content hashes.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct ModelIdentity(u64);

impl ModelIdentity {
    /// The reserved sentinel/non-cacheable identity.
    pub const NON_CACHEABLE: Self = Self(0);

    /// Raw identifier value for diagnostics/tests.
    #[must_use]
    pub fn value(self) -> u64 {
        self.0
    }
}

/// Mutation epoch paired with a [`ModelIdentity`].
#[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct MutationEpoch(u64);

impl MutationEpoch {
    /// Initial epoch for a newly wrapped model.
    pub const INITIAL: Self = Self(0);

    /// Raw epoch value for diagnostics/tests.
    #[must_use]
    pub fn value(self) -> u64 {
        self.0
    }

    fn next(self) -> Option<Self> {
        self.0.checked_add(1).map(Self)
    }
}

fn next_model_identity() -> Result<ModelIdentity, SolverError> {
    let id = NEXT_MODEL_ID
        .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |current| {
            if current == u64::MAX {
                None
            } else {
                Some(current + 1)
            }
        })
        .map_err(|_| SolverError::InternalInvariantViolation)?;
    Ok(ModelIdentity(id))
}

/// Solver-family key dimension for cached validation evidence.
#[non_exhaustive]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum SolverFamilyId {
    /// RFC 006/RFC 016 projected first-order family.
    ProjectedFirstOrder,
}

/// Problem-class key dimension for cached validation evidence.
#[non_exhaustive]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum ProblemClassId {
    /// Runtime-sized box/bound first-order problems.
    BoxBoundFirstOrder,
}

/// Scalar-family key dimension for cached validation evidence.
#[non_exhaustive]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum ScalarFamilyId {
    /// `f64`; the only cacheable scalar family in the RFC 015 slice.
    Float64,
}

/// Exact identity key for model-owned validation evidence.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct ValidationEvidenceKey {
    /// Loeres-generated model identity.
    pub model_identity: ModelIdentity,
    /// Mutation epoch for the model data.
    pub mutation_epoch: MutationEpoch,
    /// Solver family this evidence was produced for.
    pub solver_family: SolverFamilyId,
    /// Problem class this evidence was produced for.
    pub problem_class: ProblemClassId,
    /// Scalar family this evidence was produced for.
    pub scalar_family: ScalarFamilyId,
}

/// Cache lookup request: exact key plus required model-owned scope.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct ValidationEvidenceLookup {
    /// Exact evidence key.
    pub key: ValidationEvidenceKey,
    /// Model-owned validation scope required by this solve.
    pub required_model_scope: ValidationScope,
}

/// Cached model-owned validation evidence.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct CachedValidationEvidence {
    /// Model-owned scopes checked by the scan that produced this evidence.
    pub model_checked_scope: ValidationScope,
    /// How model-owned finite evidence was discharged.
    pub finite: ProjectedFirstOrderFiniteEvidence,
}

impl CachedValidationEvidence {
    pub(crate) fn validate_cacheable(
        &self,
        key: &ValidationEvidenceKey,
    ) -> Result<(), SolverError> {
        if key.model_identity == ModelIdentity::NON_CACHEABLE {
            return Err(SolverError::InvalidInput);
        }
        if key.scalar_family != ScalarFamilyId::Float64 {
            return Err(SolverError::UnsupportedProblemStructure);
        }
        match self.finite {
            ProjectedFirstOrderFiniteEvidence::Scanned => Ok(()),
            ProjectedFirstOrderFiniteEvidence::Trusted(_) => Err(SolverError::InvalidInput),
            ProjectedFirstOrderFiniteEvidence::DomainInapplicable => Err(SolverError::InvalidInput),
        }
    }
}

/// Caller-provided cached evidence for the current solve.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct ProvidedValidationEvidence {
    /// Exact key the evidence was produced for.
    pub key: ValidationEvidenceKey,
    /// Model-owned evidence payload.
    pub evidence: CachedValidationEvidence,
}

/// Host-side validation evidence cache.
#[derive(Clone, Debug, Default)]
pub struct ValidationEvidenceCache {
    entries: HashMap<ValidationEvidenceKey, CachedValidationEvidence>,
}

impl ValidationEvidenceCache {
    /// Create an empty cache.
    #[must_use]
    pub fn new() -> Self {
        Self {
            entries: HashMap::new(),
        }
    }

    /// Return matching evidence when the exact key matches and coverage is sufficient.
    #[must_use]
    pub fn get(&self, lookup: &ValidationEvidenceLookup) -> Option<CachedValidationEvidence> {
        let evidence = self.entries.get(&lookup.key).copied()?;
        if evidence
            .model_checked_scope
            .contains(lookup.required_model_scope)
        {
            Some(evidence)
        } else {
            None
        }
    }

    /// Insert cacheable scanned model-owned evidence.
    ///
    /// # Errors
    /// [`SolverError::InvalidInput`] for sentinel identities or non-cacheable
    /// evidence such as `Trusted(..)` or `DomainInapplicable` for `f64`.
    pub fn insert(
        &mut self,
        key: ValidationEvidenceKey,
        evidence: CachedValidationEvidence,
    ) -> Result<(), SolverError> {
        evidence.validate_cacheable(&key)?;
        self.entries.insert(key, evidence);
        Ok(())
    }

    /// Remove all entries for a model identity.
    pub fn invalidate_model(&mut self, identity: ModelIdentity) {
        self.entries.retain(|key, _| key.model_identity != identity);
    }

    /// Remove every cache entry.
    pub fn clear(&mut self) {
        self.entries.clear();
    }
}

/// Loeres-owned identity/epoch carrier for cacheable projected-first-order models.
pub struct CacheableProjectedFirstOrderProblem<P> {
    identity: ModelIdentity,
    epoch: MutationEpoch,
    inner: P,
    cacheable: bool,
}

impl<P> CacheableProjectedFirstOrderProblem<P> {
    /// Wrap a problem in a generated model identity at the initial epoch.
    ///
    /// # Errors
    /// [`SolverError::InternalInvariantViolation`] if the process-local identity
    /// generator is exhausted.
    pub fn new(inner: P) -> Result<Self, SolverError> {
        Ok(Self {
            identity: next_model_identity()?,
            epoch: MutationEpoch::INITIAL,
            inner,
            cacheable: true,
        })
    }

    /// The generated model identity.
    #[must_use]
    pub fn identity(&self) -> ModelIdentity {
        self.identity
    }

    /// The current mutation epoch.
    #[must_use]
    pub fn mutation_epoch(&self) -> MutationEpoch {
        self.epoch
    }

    /// Whether this carrier can currently use validation-cache evidence.
    #[must_use]
    pub fn is_cacheable(&self) -> bool {
        self.cacheable
    }

    /// Read-only access to the inner problem.
    #[must_use]
    pub fn inner(&self) -> &P {
        &self.inner
    }

    /// Mutate the inner problem after advancing the epoch.
    ///
    /// The epoch advances before the closure receives mutable access, so stale
    /// evidence fails closed even if the closure mutates and then returns an
    /// error or unwinds. If the epoch cannot advance, the carrier is marked
    /// non-cacheable and the mutation is rejected before the closure runs.
    ///
    /// # Errors
    /// Propagates the closure error, or returns
    /// [`SolverError::InternalInvariantViolation`] on epoch exhaustion.
    pub fn mutate<F>(&mut self, f: F) -> Result<(), SolverError>
    where
        F: FnOnce(&mut P) -> Result<(), SolverError>,
    {
        let Some(next_epoch) = self.epoch.next() else {
            self.cacheable = false;
            return Err(SolverError::InternalInvariantViolation);
        };
        self.epoch = next_epoch;
        f(&mut self.inner)
    }

    /// Exact key for projected-first-order `f64` model-owned evidence.
    #[must_use]
    pub fn projected_first_order_key(&self) -> ValidationEvidenceKey {
        ValidationEvidenceKey {
            model_identity: self.identity,
            mutation_epoch: self.epoch,
            solver_family: SolverFamilyId::ProjectedFirstOrder,
            problem_class: ProblemClassId::BoxBoundFirstOrder,
            scalar_family: ScalarFamilyId::Float64,
        }
    }

    /// Lookup for projected-first-order model-owned finite evidence.
    #[must_use]
    pub fn projected_first_order_lookup(&self) -> ValidationEvidenceLookup {
        ValidationEvidenceLookup {
            key: self.projected_first_order_key(),
            required_model_scope: ValidationScope::FINITE,
        }
    }
}

impl<P: Clone> Clone for CacheableProjectedFirstOrderProblem<P> {
    fn clone(&self) -> Self {
        let identity = next_model_identity().unwrap_or(ModelIdentity::NON_CACHEABLE);
        Self {
            identity,
            epoch: MutationEpoch::INITIAL,
            inner: self.inner.clone(),
            cacheable: identity != ModelIdentity::NON_CACHEABLE,
        }
    }
}

impl<P, S> ClusterProjectedFirstOrderProblem<S> for CacheableProjectedFirstOrderProblem<P>
where
    P: ClusterProjectedFirstOrderProblem<S>,
    S: FiniteScalar + MetricScalar,
{
    fn dimension(&self) -> usize {
        self.inner.dimension()
    }

    fn bounds(&self) -> (&DenseVector<S>, &DenseVector<S>) {
        self.inner.bounds()
    }

    fn gradient_at(
        &self,
        x: &DenseVector<S>,
        grad: &mut DenseVector<S>,
    ) -> Result<(), SolverError> {
        self.inner.gradient_at(x, grad)
    }

    fn step_scale(&self) -> S {
        self.inner.step_scale()
    }

    fn validate_boundary(&self) -> Result<(), SolverError> {
        self.inner.validate_boundary()
    }
}

#[cfg(test)]
mod tests;
