name: msrv
on:
  push:
    branches: [main]
  pull_request:
jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Rust 2024 edition minimum supported version.
      - uses: dtolnay/rust-toolchain@1.85.0
      - run: cargo check --workspace --all-features
